# Generated by Django 5.0.2 on 2025-03-31 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_community_event_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='created_at',
        ),
    ]
