# Generated by Django 5.0.2 on 2025-03-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_community_event_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public - Everyone can see your profile'), ('private', 'Private - Only you can see your profile'), ('friends', 'Friends Only - Only your friends can see your profile')], default='public', max_length=10),
        ),
    ]
